development:
  adapter: postgresql
  encoding: unicode
  database: copper-frog-dev
  pool: 5
  username: copperfrog
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: opper-frog-test
  pool: 5
  username: copperfrog
  password: password1
